---
- name: Installing python3
  package:
   name: python3
   state: latest

- name: Installing python3-matplotlib
  package:
   name: python3-matplotlib
   state: latest

- name: Installing python3-pandas.x86_64
  package:
   name: python3-pandas.x86_64
   state: latest
