---
- name: Installing python3
  package:
   name: python3
   state: latest

- name: Install and upgrade pandas
  pip:
    name: pandas
    extra_args: --upgrade
    executable: pip3
    
- name: Install pyalgotrade
  pip: 
   name: pyalgotrade
   extra_args: --upgrade
   executable: pip3   
